# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_branking',
            new_name='user_ranking',
        ),
        migrations.AlterModelTable(
            name='user_ranking',
            table='user_ranking',
        ),
    ]
