# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-24 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200422_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ranking',
            name='client_code',
            field=models.IntegerField(unique=True, verbose_name='客户端编号'),
        ),
    ]
