# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200424_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ranking',
            name='rank',
            field=models.IntegerField(null=True, verbose_name='排名'),
        ),
    ]
